[package]
name = "implementation"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "ap_benchmark"
harness = false

[dependencies]
rand = "0.8.5"
